### ISSUE TITLE
JavascriptClassGenerationException STJSBridge during vanilla maven build

### ISSUE THREAD

**Issue by jasonCodesAway** [st-js/st-js#109]
Hello,

I'm 99% sure I'm doing something bone-headed. I've followed the directions to get the generic plugin setup (shown below, + setting up a JAVA8_HOME environment variable pointing to JDK8), but when I do a maven install (maven 3.2.5, JDK 1.8_60) I'm seeing this exception (full stack trace below):

JavascriptClassGenerationException [className=org.stjs.javascript.annotation.STJSBridge, toString()=org.stjs.generator.JavascriptClassGenerationException: Cannot load class:java.lang.**ClassNotFoundException**: org.stjs.javascript.annotation.**STJSBridge**]

I saw on git-hub that compiling "the" project requires java 6 and java 8. Does "the" project refer to compiling st-js itself, or my (i.e. the user's) project? It doesn't seem like this would cause a ClassNotFoundException on a 'org/stjs.javascript.annotation' class, but maybe. JDK 6 is past end-of-life though, IT makes installing it hard (security issues).

Here is the relevant snippet of my pom.xml:
```xml
    <build>
        <plugins>
            <!--generate javascript from java classes-->
            <plugin>
                <groupId>org.st-js</groupId>
                <artifactId>stjs-maven-plugin</artifactId>
                <version>3.2.1</version>
                <executions>
                    <execution>
                        <id>main</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <includes>
                        <include>**/*.java</include>
                    </includes>
                </configuration>
            </plugin>
```

Full Stack Trace
```
JavascriptClassGenerationException [className=org.stjs.javascript.annotation.STJSBridge, toString()=org.stjs.generator.JavascriptClassGenerationException: Cannot load class:java.lang.ClassNotFoundException: org.stjs.javascript.annotation.STJSBridge]
	at org.stjs.generator.utils.ClassUtils.getClazz(ClassUtils.java:41)
	at org.stjs.generator.utils.ClassUtils.isBridge(ClassUtils.java:47)
	at org.stjs.generator.Generator.generateJavascript(Generator.java:144)
	at org.stjs.maven.AbstractSTJSMojo.execute(AbstractSTJSMojo.java:240)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:188)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:184)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
C:\Users\jh\work\code\direct\direct\server\src\main\java\com\direct\server\msg\Event.java [1:1]: JavascriptClassGenerationException [className=org.stjs.javascript.annotation.STJSBridge, toString()=org.stjs.generator.JavascriptClassGenerationException: Cannot load class:java.lang.ClassNotFoundException: org.stjs.javascript.annotation.STJSBridge]
JavascriptClassGenerationException [className=org.stjs.javascript.annotation.STJSBridge, toString()=org.stjs.generator.JavascriptClassGenerationException: Cannot load class:java.lang.ClassNotFoundException: org.stjs.javascript.annotation.STJSBridge]
	at org.stjs.generator.utils.ClassUtils.getClazz(ClassUtils.java:41)
	at org.stjs.generator.utils.ClassUtils.isBridge(ClassUtils.java:47)
	at org.stjs.generator.Generator.generateJavascript(Generator.java:144)
	at org.stjs.maven.AbstractSTJSMojo.execute(AbstractSTJSMojo.java:240)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:188)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:184)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
C:\Users\jh\work\code\direct\direct\server\src\main\java\com\direct\server\msg\Message.java [1:1]: JavascriptClassGenerationException [className=org.stjs.javascript.annotation.STJSBridge, toString()=org.stjs.generator.JavascriptClassGenerationException: Cannot load class:java.lang.ClassNotFoundException: org.stjs.javascript.annotation.STJSBridge]
JavascriptClassGenerationException [className=org.stjs.javascript.annotation.STJSBridge, toString()=org.stjs.generator.JavascriptClassGenerationException: Cannot load class:java.lang.ClassNotFoundException: org.stjs.javascript.annotation.STJSBridge]
	at org.stjs.generator.utils.ClassUtils.getClazz(ClassUtils.java:41)
	at org.stjs.generator.utils.ClassUtils.isBridge(ClassUtils.java:47)
	at org.stjs.generator.Generator.generateJavascript(Generator.java:144)
	at org.stjs.maven.AbstractSTJSMojo.execute(AbstractSTJSMojo.java:240)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:188)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:184)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
C:\Users\jh\work\code\direct\direct\server\src\main\java\com\direct\server\Server.java [1:1]: JavascriptClassGenerationException [className=org.stjs.javascript.annotation.STJSBridge, toString()=org.stjs.generator.JavascriptClassGenerationException: Cannot load class:java.lang.ClassNotFoundException: org.stjs.javascript.annotation.STJSBridge]
JavascriptClassGenerationException [className=org.stjs.javascript.annotation.STJSBridge, toString()=org.stjs.generator.JavascriptClassGenerationException: Cannot load class:java.lang.ClassNotFoundException: org.stjs.javascript.annotation.STJSBridge]
	at org.stjs.generator.utils.ClassUtils.getClazz(ClassUtils.java:41)
	at org.stjs.generator.utils.ClassUtils.isBridge(ClassUtils.java:47)
	at org.stjs.generator.Generator.generateJavascript(Generator.java:144)
	at org.stjs.maven.AbstractSTJSMojo.execute(AbstractSTJSMojo.java:240)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:188)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:184)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
C:\Users\jh\work\code\direct\direct\server\src\main\java\com\direct\server\msg\EventMessage.java [1:1]: JavascriptClassGenerationException [className=org.stjs.javascript.annotation.STJSBridge, toString()=org.stjs.generator.JavascriptClassGenerationException: Cannot load class:java.lang.ClassNotFoundException: org.stjs.javascript.annotation.STJSBridge]
JavascriptClassGenerationException [className=org.stjs.javascript.annotation.STJSBridge, toString()=org.stjs.generator.JavascriptClassGenerationException: Cannot load class:java.lang.ClassNotFoundException: org.stjs.javascript.annotation.STJSBridge]
	at org.stjs.generator.utils.ClassUtils.getClazz(ClassUtils.java:41)
	at org.stjs.generator.utils.ClassUtils.isBridge(ClassUtils.java:47)
	at org.stjs.generator.Generator.generateJavascript(Generator.java:144)
	at org.stjs.maven.AbstractSTJSMojo.execute(AbstractSTJSMojo.java:240)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:188)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:184)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
C:\Users\jh\work\code\direct\direct\server\src\main\java\com\direct\server\msg\MetaOperationsMessage.java [1:1]: JavascriptClassGenerationException [className=org.stjs.javascript.annotation.STJSBridge, toString()=org.stjs.generator.JavascriptClassGenerationException: Cannot load class:java.lang.ClassNotFoundException: org.stjs.javascript.annotation.STJSBridge]
JavascriptClassGenerationException [className=org.stjs.javascript.annotation.STJSBridge, toString()=org.stjs.generator.JavascriptClassGenerationException: Cannot load class:java.lang.ClassNotFoundException: org.stjs.javascript.annotation.STJSBridge]
	at org.stjs.generator.utils.ClassUtils.getClazz(ClassUtils.java:41)
	at org.stjs.generator.utils.ClassUtils.isBridge(ClassUtils.java:47)
	at org.stjs.generator.Generator.generateJavascript(Generator.java:144)
	at org.stjs.maven.AbstractSTJSMojo.execute(AbstractSTJSMojo.java:240)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:188)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:184)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Generated 0 JavaScript files in 90 ms
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 1.693 s (Wall Clock)
Finished at: 2015-10-05T15:19:53-04:00
Final Memory: 11M/307M
------------------------------------------------------------------------
Failed to execute goal org.st-js:stjs-maven-plugin:3.2.1:generate (main) on project server: Errors generating JavaScript -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by acraciun** [comment]
hi Jason,
from the stacktrace you sent us here unfortunately we're unable to reproduce the issue.
Is it possible to sent us a zip file containing the pom.xml and a Java source file that would create you this problem please? You may use my email ax.craciun at gmail.com

**Comment by jasonCodesAway** [comment]
Followed-up via e-mail as requested. Thank You!

**Comment by acraciun** [comment]
it seems that we have a dependency problem in the maven plugin (it's strange but we never actually had to compile an artifact not depending at least transitively on a STJS base artifact :).

Until we fix the problem you can add a dependency to STJS shared artifact

```xml
<dependency>
	<groupId>org.st-js</groupId>
	<artifactId>shared</artifactId>
	<version>3.2.1</version>
</dependency>
```

**Comment by jasonCodesAway** [comment]
That worked perfectly! Closing the issue, thanks for the help :)
