### ISSUE TITLE
Cannot find symbols from the same package

### ISSUE THREAD

**Issue by Tapsi** [st-js/st-js#56]
Tried everything. Changing settings, resets, different maven setups. No luck.. my code wont compile anymore. :(

Any ideas?

## Main

```
package com.company;

import org.stjs.javascript.functions.Callback0;

public class Main {

	public static void main(String[] args) {
		Integer i = 10;

		com.company.Unit unit = new com.company.Unit(10, 10);
		unit.x += 1;

		Callback0 test = new Callback0() {
			@Override public void $invoke() {

			}
		};

		unit.lamda();
	}
}
```

## Unit

```
package com.company;

import org.stjs.javascript.Array;
import org.stjs.javascript.JSCollections;
import org.stjs.javascript.JSGlobal;
import org.stjs.javascript.JSObjectAdapter;
import org.stjs.javascript.functions.Callback0;
import org.stjs.javascript.functions.Function;

public class Unit {

    public static enum TEST_ENUM {
        A,B,C
    }

    public int x;
    public int y;
    private int myPrivateVar;
    protected int myProtectedVar;

    public Unit (int x, int y) {
        this.x = x;
        this.y = y;
        myPrivateVar = 10;
        myProtectedVar = 20;
    }
    
    public void outer () {
    	int i = 1;
    }
    
    public void lamda () {
    	final Array<String> list = JSCollections.$array();

			int n = 20;
			JSObjectAdapter.$js("x = 10;");
			JSObjectAdapter.$js("x = n;");
    }

    public void checkEnum (TEST_ENUM e) {
        switch (e) {
            case A:
            case B:
            case C:
                break;
        }
    }
}
```

## Trace

```
[DEBUG] Configuring mojo 'org.st-js:maven-plugin:3.0.3:generate' with basic configurator -->
[DEBUG]   (f) buildOutputDirectory = C:\Users\Alex\Documents\CustomWars Tactics\STJS-Test\target\classes
[DEBUG]   (f) compileSourceRoots = [C:\Users\Alex\Documents\CustomWars Tactics\STJS-Test\src\main\java]
[DEBUG]   (f) generateArrayHasOwnProperty = true
[DEBUG]   (f) generateSourceMap = false
[DEBUG]   (f) includes = [**/*.java]
[DEBUG]   (f) pack = true
[DEBUG]   (f) project = MavenProject: groupId:STJS-Test:1.0-SNAPSHOT @ C:\Users\Alex\Documents\CustomWars Tactics\STJS-Test\pom.xml
[DEBUG]   (f) staleMillis = 0
[DEBUG] -- end configuration --
[INFO] Generating JavaScript files to C:\Users\Alex\Documents\CustomWars Tactics\STJS-Test\target\classes
[DEBUG] Classpath:C:\Users\Alex\Documents\CustomWars Tactics\STJS-Test\target\classes
[DEBUG] Classpath:C:\Users\Alex\.m2\repository\org\st-js\bridge\html\5.0.bv2\html-5.0.bv2.jar
[DEBUG] Classpath:C:\Users\Alex\.m2\repository\org\st-js\shared\3.0.0\shared-3.0.0.jar
[DEBUG] Classpath:C:\Users\Alex\.m2\repository\org\st-js\server\3.0.3\server-3.0.3.jar
[DEBUG] Generating C:\Users\Alex\Documents\CustomWars Tactics\STJS-Test\target\classes\com\company\Unit.js
[DEBUG] Generating C:\Users\Alex\Documents\CustomWars Tactics\STJS-Test\target\classes\com\company\Main.js
C:\Users\Alex\Documents\CustomWars Tactics\STJS-Test\src\main\java\com\company\Main.java:10: error: cannot find symbol
		com.company.Unit unit = new com.company.Unit(10, 10);
		           ^
  symbol:   class Unit
  location: package com.company
C:\Users\Alex\Documents\CustomWars Tactics\STJS-Test\src\main\java\com\company\Main.java:10: error: cannot find symbol
		com.company.Unit unit = new com.company.Unit(10, 10);
		                                       ^
  symbol:   class Unit
  location: package com.company
[ERROR] C:\Users\Alex\Documents\CustomWars Tactics\STJS-Test\src\main\java\com\company\Main.java [1:1]: java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$ClassSymbol cannot be cast to javax.lang.model.element.ExecutableElement
java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$ClassSymbol cannot be cast to javax.lang.model.element.ExecutableElement
	at org.stjs.generator.javac.TreeUtils.elementFromUse(TreeUtils.java:432)
	at org.stjs.generator.check.expression.MethodInvocationOuterScopeCheck.visit(MethodInvocationOuterScopeCheck.java:36)
	at org.stjs.generator.check.expression.MethodInvocationOuterScopeCheck.visit(MethodInvocationOuterScopeCheck.java:22)
	at org.stjs.generator.visitor.TreePathScannerContributors$ContributorHolder.visitContributors(TreePathScannerContributors.java:258)
	at org.stjs.generator.visitor.TreePathScannerContributors$ContributorHolder.visit(TreePathScannerContributors.java:251)
	at org.stjs.generator.visitor.TreePathScannerContributors.visit(TreePathScannerContributors.java:187)
	at org.stjs.generator.visitor.TreePathScannerContributors.scan(TreePathScannerContributors.java:202)
	at org.stjs.generator.visitor.TreePathScannerContributors.scan(TreePathScannerContributors.java:18)
	at com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:243)
	at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1302)
	at org.stjs.generator.visitor.TreePathScannerContributors.visit(TreePathScannerContributors.java:189)
	at org.stjs.generator.visitor.TreePathScannerContributors.scan(TreePathScannerContributors.java:202)
	at org.stjs.generator.visitor.TreePathScannerContributors.scan(TreePathScannerContributors.java:18)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:81)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
	at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:162)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:918)
	at org.stjs.generator.visitor.TreePathScannerContributors.visit(TreePathScannerContributors.java:189)
	at org.stjs.generator.visitor.TreePathScannerContributors.scan(TreePathScannerContributors.java:202)
	at org.stjs.generator.visitor.TreePathScannerContributors.scan(TreePathScannerContributors.java:18)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:81)
	at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:144)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:800)
	at org.stjs.generator.visitor.TreePathScannerContributors.visit(TreePathScannerContributors.java:189)
	at org.stjs.generator.visitor.TreePathScannerContributors.scan(TreePathScannerContributors.java:202)
	at org.stjs.generator.visitor.TreePathScannerContributors.scan(TreePathScannerContributors.java:18)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:81)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:99)
	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:133)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
	at org.stjs.generator.visitor.TreePathScannerContributors.visit(TreePathScannerContributors.java:189)
	at org.stjs.generator.visitor.TreePathScannerContributors.scan(TreePathScannerContributors.java:202)
	at org.stjs.generator.visitor.TreePathScannerContributors.scan(TreePathScannerContributors.java:18)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:99)
	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:120)
	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:550)
	at org.stjs.generator.visitor.TreePathScannerContributors.visit(TreePathScannerContributors.java:189)
	at org.stjs.generator.visitor.TreePathScannerContributors.scan(TreePathScannerContributors.java:202)
	at org.stjs.generator.Generator.generateJavascript(Generator.java:177)
	at org.stjs.maven.AbstractSTJSMojo.execute(AbstractSTJSMojo.java:240)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] Generated 1 JavaScript files in 733 ms
[DEBUG] Classpath:C:\Users\Alex\Documents\CustomWars Tactics\STJS-Test\target\classes
[DEBUG] Classpath:C:\Users\Alex\.m2\repository\org\st-js\bridge\html\5.0.bv2\html-5.0.bv2.jar
[DEBUG] Classpath:C:\Users\Alex\.m2\repository\org\st-js\shared\3.0.0\shared-3.0.0.jar
[DEBUG] Classpath:C:\Users\Alex\.m2\repository\org\st-js\server\3.0.3\server-3.0.3.jar
[DEBUG] com.company.Main is a bridge. Don't add it to the pack file
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.816 s
[INFO] Finished at: 2015-01-11T22:25:51+01:00
[INFO] Final Memory: 19M/143M
```

**Comment by Tapsi** [comment]
I've found the error. Seems the stjs compiler cannot compile my project because the path contains a space character. It works like expected after renaming _CustomWars Tactics_ to _CustomWarsTactics_.

**Comment by MdAbulHossain1** [comment]
@charlesdemers
