### ISSUE TITLE
stjs compiler fails if path has a space in it

### ISSUE THREAD

**Issue by vakopian** [st-js/st-js#61]
When the full path to the java file contains a space the stjs compiler fails with a strange exception.
Here is the stack trace

```
[ERROR] /home/jenkins/jobs/my  test project/workspace/test/src/main/java/com/example/Test.java [1:1]: java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$ClassSymbol cannot be cast to javax.lang.model.element.ExecutableElement
java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$ClassSymbol cannot be cast to javax.lang.model.element.ExecutableElement
        at org.stjs.generator.javac.TreeUtils.elementFromUse(TreeUtils.java:432)
        at org.stjs.generator.check.expression.MethodInvocationOuterScopeCheck.visit(MethodInvocationOuterScopeCheck.java:36)
        at org.stjs.generator.check.expression.MethodInvocationOuterScopeCheck.visit(MethodInvocationOuterScopeCheck.java:22)
        at org.stjs.generator.visitor.TreePathScannerContributors$ContributorHolder.visitContributors(TreePathScannerContributors.java:258)
        at org.stjs.generator.visitor.TreePathScannerContributors$ContributorHolder.visit(TreePathScannerContributors.java:251)
        at org.stjs.generator.visitor.TreePathScannerContributors.visit(TreePathScannerContributors.java:187)
        at org.stjs.generator.visitor.TreePathScannerContributors.scan(TreePathScannerContributors.java:202)
        at org.stjs.generator.visitor.TreePathScannerContributors.scan(TreePathScannerContributors.java:18)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:80)
        at com.sun.source.util.TreeScanner.visitAssignment(TreeScanner.java:294)
        at com.sun.tools.javac.tree.JCTree$JCAssign.accept(JCTree.java:1473)
        at org.stjs.generator.visitor.TreePathScannerContributors.visit(TreePathScannerContributors.java:189)
        at org.stjs.generator.visitor.TreePathScannerContributors.scan(TreePathScannerContributors.java:202)
        at org.stjs.generator.visitor.TreePathScannerContributors.scan(TreePathScannerContributors.java:18)
        at com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:240)
        at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1173)
        at org.stjs.generator.visitor.TreePathScannerContributors.visit(TreePathScannerContributors.java:189)
        at org.stjs.generator.visitor.TreePathScannerContributors.scan(TreePathScannerContributors.java:202)
        at org.stjs.generator.visitor.TreePathScannerContributors.scan(TreePathScannerContributors.java:18)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:80)
        at com.sun.source.util.TreeScanner.scan(TreeScanner.java:90)
        at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:159)
        at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:790)
        at org.stjs.generator.visitor.TreePathScannerContributors.visit(TreePathScannerContributors.java:189)
        at org.stjs.generator.visitor.TreePathScannerContributors.scan(TreePathScannerContributors.java:202)
        at org.stjs.generator.visitor.TreePathScannerContributors.scan(TreePathScannerContributors.java:18)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:80)
        at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:142)
        at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:690)
        at org.stjs.generator.visitor.TreePathScannerContributors.visit(TreePathScannerContributors.java:189)
        at org.stjs.generator.visitor.TreePathScannerContributors.scan(TreePathScannerContributors.java:202)
        at org.stjs.generator.visitor.TreePathScannerContributors.scan(TreePathScannerContributors.java:18)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:80)
        at com.sun.source.util.TreeScanner.scan(TreeScanner.java:90)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:98)
        at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:132)
        at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:618)
        at org.stjs.generator.visitor.TreePathScannerContributors.visit(TreePathScannerContributors.java:189)
        at org.stjs.generator.visitor.TreePathScannerContributors.scan(TreePathScannerContributors.java:202)
        at org.stjs.generator.visitor.TreePathScannerContributors.scan(TreePathScannerContributors.java:18)
        at com.sun.source.util.TreeScanner.scan(TreeScanner.java:90)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:98)
        at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:119)
        at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:492)
        at org.stjs.generator.visitor.TreePathScannerContributors.visit(TreePathScannerContributors.java:189)
        at org.stjs.generator.visitor.TreePathScannerContributors.scan(TreePathScannerContributors.java:202)
        at org.stjs.generator.Generator.generateJavascript(Generator.java:177)
        at org.stjs.maven.AbstractSTJSMojo.execute(AbstractSTJSMojo.java:240)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
```

If I remove the space in `my  test project`, everything works fine.
The same issue was reported in #56

**Comment by npiguet** [comment]
We are still completely unable to reproduce this. Can you make a github repo where the problem can be reproduced?

**Comment by acraciun** [comment]
As we are unable to reproduce this, please open it with a small repo example to that we have enough info to fix it
